abel: Guatemala departaments
centroids: gtm_municipalities-centroids.csv
altids: 
altnames: 
regions: 
topojson:
  scope: XXX
  geographyName: name
  geographyId: id
  path: gtm_municipalities.topojson
projections:
  mercator:
    name: mercator
    center: [-90.30, 16.22]
    rotate: [0, 0]
    scale: 5.5
    translate: [0,0]
  equirectangular:
    name: mercator
    center: [-90.30, 16.22]
    rotate: [0, 0]
    scale: 5.5
    translate: [0,0]
