label: Colombia departaments
centroids: col-adm1-departments.csv
altnames: col-adm1-departments-altnames.csv
regions: col-adm1-regions.csv
topojson:
  scope: depto
  geographyName: name
  geographyId: id
  path: col-adm1-departments.topojson
projections:
  mercator:
    center: [-73.5, 4.2]
    rotate: [0, 0]
    scale: 1.8
    translate: [0,0]
  equirectangular:
    center: [-73.5, 4.2]
    rotate: [0, 0]
    scale: 1.8
    translate: [0,0]
